# Change these first
owner: YT-Advanced # Your GitHub organization or username, where this repository lives
repo: tbcpcoj # The name of this repository

sites:
  - name: TBCPC
    url: https://oj.tbcpc.id.vn

status-website:
  # cname: demo.upptime.js.org
  baseUrl: /YT-Advanced
  logoUrl: https://tbcpclub.github.io/tbcpcimg/TBCPC.ico
  name: TBCPC Status
  introTitle: "Uptime for TBCPC"
  introMessage: This is a sample status page which uses **real-time** data. No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
